### ISSUE TITLE
commonbike.nl refers to mobilock.nl

### ISSUE THREAD

**Issue by bartwr** [CommonBike/commonbike-site#101]
Is a bit confusing. Was that always the case?

commonbike.com still loads the CommonBike informational site, so that's good.

**Comment by mymobility1** [comment]
Ai, maybe we are not the owner of Commonbike.nl, not very cool if the mobilocks guys did this, as they earlier refused to participate in commonbike.

**Comment by mymobility1** [comment]
One of the owners of Mobilock registerded commonbike.nl. see whois: 

Administratieve contactpersoon i | walter@mobilock.nl
-- | --

**Comment by bartwr** [comment]
Ok. MobiLock registered commonbike.nl after we've started communicating the name and project named CommonBike. No problem, we have common.bike and commonbike.com. I close this issue now, question answered.
