### ISSUE TITLE
The developer should be able to deploy to Heroku

### ISSUE THREAD

**Issue by bartwr** [CommonBike/commonbike-site#103]
[Heroku](http://herokuapp.com/) is a cloud application platform.

A while ago @pve did mention it could be nice to make CommonBike a "Continues Integration" (CI) project. This means: make it easy to deploy, and make new code automatically deploy after automated tests are finished.

I think we could start making deployments more efficient and easier to manage by starting to use Heroku. As long as CommonBike is 'small', this is free. If CommonBike is gaining more users, we can upgrade.

I will do some preparation to bring CommonBike from DigitalOcean (where it's hosted on my account at the moment) to HerokuApp.

**Comment by pve** [comment]
I already have this working. Whenever there is a deployment to 
https://github.com/pve/commonbike-site-2 branch develop
travis-ci will deploy it to heroku at https://pve-commonbike-site.herokuapp.com/

The big thing is that this will enable automatic testing at Travis. 
I should be able to clone from a Commonbike site branch, as well as send notifications to the commonbike slack channel.

**Comment by pve** [comment]
Here is a repo to show you how to do continuous testing with Mocha: 
https://github.com/pve/meteor-ci-demo
which is deployed by
https://travis-ci.org/pve/meteor-ci-demo to https://pve-meteor-ci-demo.herokuapp.com/

**Comment by bartwr** [comment]
@pve Yes, very nice.

I have created a [pull request](https://github.com/CommonBike/commonbike-site/pull/104), so we will have this feature in the develop branch of https://github.com/CommonBike/commonbike-site repo as well.

I'll use Mocha tests for new features, so in the future we will have safe automatic deployments.
