### ISSUE TITLE
location management: change title for administrator mode

### ISSUE THREAD

**Issue by mosbuma** [CommonBike/commonbike-site#14]
Currently the admin page for location says "Haal je fiets bij xxxxxxxx. Kies hieronder je gewenste fiets" -> is confusing. Change to something like "Beheer hier locatie xxxxxxx".

**Comment by RonaldHav** [comment]
Might be better to remove the text. Minder is meer ....
Remove: "Haal je fiets bij"
Remove "Kies hieronder je gewenste fiets"
