### ISSUE TITLE
client/server directory structure

### ISSUE THREAD

**Issue by ericvrp** [CommonBike/commonbike-site#17]
We need to put files in the imports directory in a client/server subdirectory to speedup Meteor restarts. And also to avoid issues with packages that are intended on one side (most client) only.

**Comment by bartwr** [comment]
Yes. (Everytime I start working on a file I'll move it to the right folder first.)

**Comment by bartwr** [comment]
This issue is closed by pull request #21. Again, thank you for mentioning this.
