### ISSUE TITLE
Aanmelden via google, facebook en github werkt niet (meer)

### ISSUE THREAD

**Issue by RonaldHav** [CommonBike/commonbike-site#18]
surf naar common.bike (al dan niet in incognito venster)
kies aanmelden
Klik op google icoon
response : SERVICE NOT CONFIGURED

idem bij klikken op Facebook
Bij klikken op Github gebeurt er niets.

{komt dit door overzetten naar nieuwe server}?

**Comment by bartwr** [comment]
Oorzaak is inderdaad de verhuizing. Ik wist dat ik nog een aantal onderdelen moest configureren - doe ik snel. Wat moet gebeuren:

- Instellingen social media login verhuizen van oude naar nieuwe server
- Database (met gebruikers e.d.) verhuizen van oude naar nieuwe server

Doe ik snel.

**Comment by bartwr** [comment]
I migrated the database with login settings from the old server to the new server at DigitalOcean.

The social login services work again, see https://common.bike/login
