### ISSUE TITLE
Location management broken

### ISSUE THREAD

**Issue by mosbuma** [CommonBike/commonbike-site#24]
Currently all locations are visible to all users in location admin mode

**Comment by mosbuma** [comment]
@bartwr the Meteor.subscribe('locations') in client/main.js that was added in the last merge breaks the location management. Is there a component dependent on this?

**Comment by bartwr** [comment]
`Meteor.subscribe('locations') was originally added by me, [here](https://github.com/CommonBike/commonbike-site/commit/a67075917cb33ab523eb9ed62fba228f9d78e1f6#diff-096103d8490b885f9d5037baea6aea80R1).

I will fix this now by only subscribing [in](https://github.com/CommonBike/commonbike-site/commit/a67075917cb33ab523eb9ed62fba228f9d78e1f6#diff-c1edeaeebe6f24813847e5dd3d7a9465R45) the `LocationDetails` component.
