### ISSUE TITLE
Add EasyFiets bikes, so we can start with the pilot

### ISSUE THREAD

**Issue by bartwr** [CommonBike/commonbike-site#29]

**Comment by bartwr** [comment]
UPDATE: @RonaldHav added the locations in Leiden, see screenshot below.

NEXT: We have to think about how we add the EasyFiets bikes to each location page.

![image](https://cloud.githubusercontent.com/assets/899234/21963322/2fa965f6-db39-11e6-822a-d8fae3fbf461.png)

**Comment by RonaldHav** [comment]
I can bike around and have a look which bikes are at the locations at the moment and put them into the system.
