### ISSUE TITLE
Location Address in UI

### ISSUE THREAD

**Issue by ericvrp** [CommonBike/commonbike-site#32]
We now set the address in the testuser data and have not yet a way to set it in the UI

**Comment by ericvrp** [comment]
not sure if this needs for the MVP

**Comment by RonaldHav** [comment]
For MVP Lat lon locations are on [map](https://drive.google.com/open?id=1nfszOoBFlvrjoZUPaJHJ1Durnsk&usp=sharing)
We start with the 4 locations in Leiden

**Comment by ericvrp** [comment]
Hi Marc, it looks like most of them are already part of the testdata. Could you please the bottom few of the list also?

**Comment by ericvrp** [comment]
Coordinates can now be set in the UI. There is no relation between the coordinate and the textual address. Closing this issue because this is now functional complete.
