### ISSUE TITLE
A user can only be location provider if logged in with email / password combination

### ISSUE THREAD

**Issue by bartwr** [CommonBike/commonbike-site#39]
It should be possible make a user a location provider independent of the way the user logs in.

![image](https://cloud.githubusercontent.com/assets/899234/21962192/20030b52-db20-11e6-8ff8-ea8f56dfc73c.png)

**Comment by mosbuma** [comment]
Agree. I have no sample data of users that have registered with other services than email, so will have to make the other services work at my local develop server to see how this can be done...

**Comment by mosbuma** [comment]
Have looked at this: don't see an easy solution here. If we allow arbitrary user search here (or a dropdown with all users) and return a list of matching names it becomes possible to query the user list, which does not seem like a good idea to me... some OAuth providers (facebook/twitter) don't register email adresses so I can not extend the search to the other providers... other ideas are welcome.

**Comment by bartwr** [comment]
Let's make sure that admins and location providers have an email address connected to their login account. Then we can add those users as location provider by using their email address, just like it works already.

**Comment by RonaldHav** [comment]
great solved for now
