### ISSUE TITLE
Switch Flow Router -> react_router

### ISSUE THREAD

**Issue by ericvrp** [CommonBike/commonbike-site#4]
This is just my opinion but I think we should switch from the Flow router Meteor package to the better maintained and more widely used npm react-router package.

**Comment by bartwr** [comment]
(I'm not experienced in JavaScript routers. I know FlowRouter and IronRouter best.)

Can you tell about the advantages of `react-router` compared to the other high valuable routers?

Also, would you like to implement `react-router` yourself, or shall I / should someone else do it?

**Comment by ericvrp** [comment]
I have worked with these three routers and my code seems most simple with react-router but this is not necessarily because the router is better.

On Github Flow router has 1024 stars and react-router 18250.  I would pick react-router also because of this blog by the Flow router author https://voice.kadira.io/its-time-thank-you-bye-meteor-115dd649a8#.j8gflfe6k

At the moment they would probably all work equaly well. I will have a go at switching router in a branch. When it's done we can have a look and decide what to keep.

**Comment by bartwr** [comment]
Thanks!

**Comment by ericvrp** [comment]
I will be working on this in https://github.com/CommonBike/commonbike-site/tree/feature/react-router

**Comment by bartwr** [comment]
This issue is closed since pull request #15 is merged into `develop`.

Good that you mentioned this improvement, because `react-router` will be maintained for a longer time, and presumably more people know the library.
