### ISSUE TITLE
improve tekst on /login screen for people who are waiting to be invited

### ISSUE THREAD

**Issue by RonaldHav** [CommonBike/commonbike-site#41]
current=old text:
Leuk dat je meedoet! We sturen je als eerste een bericht als de app gebruikt kan worden.
In december starten we een pilot bij een intercity treinstation. Daarna breiden we uit.
[Log out]

->

Leuk dat je mee wilt doen!
We zijn gestart met een besloten gebruikersgroep in Leiden. Mail ons (info@commonbike.com) als je nu al mee wilt fietsen en testen in Leiden.

We sturen je als eerste een bericht als we uitbreiden.

[Hoe werkt commonbike] LINK commonbike.com

[uitloggen]

**Comment by bartwr** [comment]
Ik twijfel: is het beter om "Hoe werkt CommonBike?" te linken aan http://commonbike.com/ of https://common.bike/join ?

**Comment by RonaldHav** [comment]
kan allebei, maar volgens mij zie je dit scherm alleen als je ingelogd bent en dus al aangemeld hebt.
Dan zou linken naar /help het beste zijn, nadat we die gemaakt hebben.

Die /help lijkt me ook fijn omdat we dan de teksten in de hoofdschermen (de flow) minimaal kunnen houden en op /help wat kunnen uitleggen
