### ISSUE TITLE
"Mijn verhuur" shows no rental although a bike is rented

### ISSUE THREAD

**Issue by RonaldHav** [CommonBike/commonbike-site#44]
User Ronald (with google sign in = admin)
I rented a bike [Easy 1] at [Leiden Centraal]
[Leiden centraal is shown at [mijn locaties]

[mijn verhuur] shows no bikes [ER ZIJN GEEN FIETSEN VERHUURD]

**Comment by RonaldHav** [comment]
Ohh, Maybee do I THINK I am location owner because I see all the locations as an ADMIN but I am not really a location owner.

It might be good to see all  rental activities as an ADMIN (on all the locations)

**Comment by bartwr** [comment]
@RonaldHav Indeed: you are an admin, but no location owner. That is the reason you see 'NO BIKES RENTED'. Let's fix this and make sure that admins see all rented bikes of all locations.
