### ISSUE TITLE
The [stap op] button jumps tot [terugbrengen] now

### ISSUE THREAD

**Issue by RonaldHav** [CommonBike/commonbike-site#45]
@bartwr : Er is iets mis gegaan met aanpassen tekst button [huur] -> stap op.
Nu krijg je niet meer het scherm wat je aan de stallinghouder moet laten zien, maar krijg je het scherm van tergubrengen.

ps heb je screenshot van scherm dat aan stallinghouder getoond moet worden voor instructiecard?

**Comment by RonaldHav** [comment]
seems to be al right now

**Comment by mosbuma** [comment]
Can still reproduce this. Happens when you reserve/rent a bike, return it and immediately reserve/rent it again

**Comment by bartwr** [comment]
@RonaldHav 

Screenshots of the page that the user can show to a human location provider:

![image](https://cloud.githubusercontent.com/assets/899234/21986098/4e1e3a28-dbfe-11e6-8cda-1cf9c5cf04be.png)

![image](https://cloud.githubusercontent.com/assets/899234/21986107/57df3f3a-dbfe-11e6-8705-ec1158e3ab93.png)
