### ISSUE TITLE
As admin I can not admin the bikes

### ISSUE THREAD

**Issue by RonaldHav** [CommonBike/commonbike-site#47]
At which screen I have to admin bikes?
This functionality seems to be lost (for admin?)

Bikes at Leiden CS are 564 and 667

**Comment by mosbuma** [comment]
Nieuwe reservering -> Admin Locations -> Select Location and click Info

From there you can add/delete bikes

At the moment there is no GUI yet for setting key IDs etc.

**Comment by RonaldHav** [comment]
OK, sorry, die route had ik over het hoofd gezien.
Done!
