### ISSUE TITLE
screen [mijn verhuur] needs to show since when a bike is rented out and or who renter is

### ISSUE THREAD

**Issue by RonaldHav** [CommonBike/commonbike-site#49]
This info is essential for a location owner to manage his fleet.
When a bike is away for more than 25 hours he might want to take some action.

**Comment by mosbuma** [comment]
@RonaldHav Items now show renter's email + the duration of the rent. Is this sufficient?

**Comment by RonaldHav** [comment]
Yes, this is super!
(Maybe we should ask @SintK Friday to have a look at design for bigger (wider) screen)
