### ISSUE TITLE
There is no route for the path: /admin

### ISSUE THREAD

**Issue by bartwr** [CommonBike/commonbike-site#5]
Right now only `/admin/location` and `/admin/:locationId` are available.

Suggestion:

- Make `/admin` show a basic dashboard. If there is no data to show, show a random bike from the Web.

**Comment by ericvrp** [comment]
Fixed by https://github.com/CommonBike/commonbike-site/pull/7

**Comment by bartwr** [comment]
Fixed by @ericvrp in #7 (commit [de01dd3a683bb8a625ea84238de942e344c29bca](https://github.com/CommonBike/commonbike-site/commit/de01dd3a683bb8a625ea84238de942e344c29bca))

edit: whoops, duplicate
