### ISSUE TITLE
Improve sceen to be shown to stallinghouder

### ISSUE THREAD

**Issue by RonaldHav** [CommonBike/commonbike-site#53]
In Leiden Easyfiets system "huurcode" is confusing for stallinghouders and bike number is difficult to read because small font.

-> Can we define a bike type for which there is no "huurcode"shown"?

-> can we move text "Toon onderstaande huurcode aan de medewerker en vraag om de sleutel." down and shorten:  "Toon dit scherm aan de medewerker en vraag om de sleutel.

--> replace tekst "Hiermee kunt u [[Easyfiets V12]] openen. -> [[Easyfiets V12]] in huge font

-->text next to photo: Why is there [verhuurd] on this screen? The user has rented this bike. better nothing here of "your bike"
No need tot display price here. {in general do not bother customer with the price too much. the decision to rent is already made, no need to remember him the price.}

**Comment by mosbuma** [comment]
@RonaldHav is the screen alright with the latest changes?

**Comment by RonaldHav** [comment]
Much better! awesome
(there is still a onrange line under the [strip with bike picture] that is not in the design (but is a minor thing)
It shoud be better to have the tekst "Toon dit scherm ... sleutel"UNDER the big [Eseafiets V5] becouse you still need to scroll the picture you have to show stallinghouder.

For now it is great, it might be better to ask advice @SintK for a uniform design.
