### ISSUE TITLE
Improve docs for setting up a local development environment

### ISSUE THREAD

**Issue by ericvrp** [CommonBike/commonbike-site#6]
We need more pointers to or better instructions for setting up a working local development environment. At the moment I can not log in with email (need to find out why not) while the Facebook/Twitter... login gives 'service not configured' errors in the console. The links in Login.jsx to their control panels seem to be of a non-public accessable account.

**Comment by ericvrp** [comment]
Fix for email login button proposed in PR https://github.com/CommonBike/commonbike-site/pull/7

**Comment by bartwr** [comment]
I'll improve the docs. If you have additions: please add those to your wish.

**Comment by bartwr** [comment]
I updated `README.md` and added a new `DEVELOP.md`.

One of the new sections in `DEVELOP.md` is *[Configuring login services like Facebook and Twitter](https://github.com/CommonBike/commonbike-site/blob/develop/DEVELOP.md#configuring-login-services-like-facebook-and-twitter)*.
