### ISSUE TITLE
Strip HTML from object titles (bike/location)

### ISSUE THREAD

**Issue by bartwr** [CommonBike/commonbike-site#63]
The way I created the bike/location editor makes it possible to add HTML into object titles. Suggestion: disable this functionality (or make it impossible to add returns into the title).

![image](https://cloud.githubusercontent.com/assets/899234/22197967/a7c974ba-e154-11e6-8b39-fee0fd5e842a.png)

**Comment by hlgrondijs** [comment]
Ik ga dit proberen op te lossen, succes niet gegarandeerd!

**Comment by bartwr** [comment]
Fixed in #64!
